### ISSUE TITLE
Intel video analytics application used in the Camera management example app service is not available

### ISSUE THREAD

**Issue by ramams** [edgexfoundry/edgex-examples#244]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: Camera Management service

### Is this a regression?

 Not sure. This is the first time I am trying this example service.

## 🔥 Exception or Error
<pre><code>

$ make install-edge-video-analyticsmake -C edge-video-analytics install
git clone --depth=1 --branch v0.7.2 https://github.com/intel/edge-video-analytics-microservice.git src_v0.7.2
Cloning into 'src_v0.7.2'...
Username for 'https://github.com': ramams
Password for 'https://ramams@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/intel/edge-video-analytics-microservice.git/' not found
make[1]: *** [Makefile:18: src_v0.7.2] Error 128

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 22.04.3

**EdgeX Version [**REQUIRED**]:** 3.1.1

**Anything else relevant?** It seems like the camera management app uses an Intel open source application for video inference. Make command is trying to check out the code from https://github.com/intel/edge-video-analytics-microservice.git, which is not available any more. I checked Intel Github repositories and I do not find this repository. Is there any alternative for trying out the camera management service? Thank you!

**Comment by cloudxxx8** [comment]
@ramams sorry, we don't have any alternative solution.
@jumpingliu  please help remove the Camera Management service and the related docs from the main branch, since we can't support it anymore
https://github.com/edgexfoundry/edgex-examples/tree/main/application-services/custom/camera-management
https://docs.edgexfoundry.org/3.2/examples/app-service-examples/camera-management/Ch-CameraManagement/

**Comment by ramams** [comment]
Thanks for the update!
